# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
       # Installs Dependencies
    - name: Install Dependencies
      run: npm install
 
  
    # Runs a set of commands using the runners shell
    - name: Build
      run: npm run build
      
      # Runs a set of commands using the runners shell
    - name: Status
      run: git status
      
      # Runs a set of commands using the runners shell
    - name: Add
      run: git add .
    
     # Runs a set of commands using the runners shell
    - name: email
      run: git config --global user.email "codetheorem.dev@gmail.com"
      
    - name: name 
      run:  git config --global user.name "Hrishikesh Agarwal"
        
    - name: commit 
      run:  git commit -m "added dist folder"
 
     
      
      # Runs a set of commands using the runners shell
    - name: push
      run: git push
